from typing import Sequence

class _Naming:
    def __init__(self, _name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def tags(self) -> set[str]: ...

class Naming(_Naming):
    @classmethod
    def get_database(cls) -> dict[str, Sequence[str]]: ...
    def equal(self, otherNameData: _Naming | str, must_be_the_same: bool = ...) -> bool: ...
