# coding: utf-8

"""
    Synctera API

    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>  # noqa: E501

    The version of the OpenAPI document: 1.41.3
    Contact: dev@swadesh.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from synctera_client_v1.models.transaction1 import Transaction1

class PaginatedTransactions(BaseModel):
    """
    PaginatedTransactions
    """
    next_page_token: Optional[StrictStr] = Field(..., description="If returned, use the value of `next_page_token` in the `page_token` query parameter to query for the next page of results. This will be `null` if there are no more pages.")
    transactions: conlist(Transaction1) = Field(..., description="List of transactions")
    __properties = ["next_page_token", "transactions"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PaginatedTransactions:
        """Create an instance of PaginatedTransactions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item in self.transactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['transactions'] = _items
        # set to None if next_page_token (nullable) is None
        # and __fields_set__ contains the field
        if self.next_page_token is None and "next_page_token" in self.__fields_set__:
            _dict['next_page_token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PaginatedTransactions:
        """Create an instance of PaginatedTransactions from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return PaginatedTransactions.parse_obj(obj)

        _obj = PaginatedTransactions.parse_obj({
            "next_page_token": obj.get("next_page_token"),
            "transactions": [Transaction1.from_dict(_item) for _item in obj.get("transactions")] if obj.get("transactions") is not None else None
        })
        return _obj

