# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.1.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.models.body32 import Body32  # noqa: E501
from obp_python.rest import ApiException


class TestBody32(unittest.TestCase):
    """Body32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody32(self):
        """Test Body32"""
        # FIXME: construct object with mandatory attributes with example values
        # model = obp_python.models.body32.Body32()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
