# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.1.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.models.inline_response20021_foo_bar import InlineResponse20021FooBar  # noqa: E501
from obp_python.rest import ApiException


class TestInlineResponse20021FooBar(unittest.TestCase):
    """InlineResponse20021FooBar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20021FooBar(self):
        """Test InlineResponse20021FooBar"""
        # FIXME: construct object with mandatory attributes with example values
        # model = obp_python.models.inline_response20021_foo_bar.InlineResponse20021FooBar()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
