# coding: utf-8

"""
    Open Bank Project API

    An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2023. Licensed under the AGPL and commercial licences.  # noqa: E501

    OpenAPI spec version: v5.1.0
    Contact: contact@tesobe.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import obp_python
from obp_python.models.inline_response20051_sustrans import InlineResponse20051Sustrans  # noqa: E501
from obp_python.rest import ApiException


class TestInlineResponse20051Sustrans(unittest.TestCase):
    """InlineResponse20051Sustrans unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20051Sustrans(self):
        """Test InlineResponse20051Sustrans"""
        # FIXME: construct object with mandatory attributes with example values
        # model = obp_python.models.inline_response20051_sustrans.InlineResponse20051Sustrans()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
