# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/hc/Syf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.hc import ResultsDetailLevel_pb2 as zepben_dot_protobuf_dot_hc_dot_ResultsDetailLevel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1czepben/protobuf/hc/Syf.proto\x12\x12zepben.protobuf.hc\x1a+zepben/protobuf/hc/ResultsDetailLevel.proto\"\xd0\x02\n\x03Syf\x12\x10\n\x08scenario\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\x0e\n\x06\x66\x65\x65\x64\x65r\x18\x03 \x01(\t\x12M\n\x13installedTxCapacity\x18\x04 \x03(\x0b\x32\x30.zepben.protobuf.hc.Syf.InstalledTxCapacityEntry\x12\x12\n\nnormVMinPu\x18\x05 \x01(\x01\x12\x12\n\nnormVMaxPu\x18\x06 \x01(\x01\x12\x42\n\x12resultsDetailLevel\x18\x07 \x01(\x0e\x32&.zepben.protobuf.hc.ResultsDetailLevel\x12\"\n\x1aqualityAssuranceProcessing\x18\x08 \x01(\x08\x1a:\n\x18InstalledTxCapacityEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x42/\n\x16\x63om.zepben.protobuf.hcP\x01\xaa\x02\x12Zepben.Protobuf.HCb\x06proto3')



_SYF = DESCRIPTOR.message_types_by_name['Syf']
_SYF_INSTALLEDTXCAPACITYENTRY = _SYF.nested_types_by_name['InstalledTxCapacityEntry']
Syf = _reflection.GeneratedProtocolMessageType('Syf', (_message.Message,), {

  'InstalledTxCapacityEntry' : _reflection.GeneratedProtocolMessageType('InstalledTxCapacityEntry', (_message.Message,), {
    'DESCRIPTOR' : _SYF_INSTALLEDTXCAPACITYENTRY,
    '__module__' : 'zepben.protobuf.hc.Syf_pb2'
    # @@protoc_insertion_point(class_scope:zepben.protobuf.hc.Syf.InstalledTxCapacityEntry)
    })
  ,
  'DESCRIPTOR' : _SYF,
  '__module__' : 'zepben.protobuf.hc.Syf_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.hc.Syf)
  })
_sym_db.RegisterMessage(Syf)
_sym_db.RegisterMessage(Syf.InstalledTxCapacityEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.zepben.protobuf.hcP\001\252\002\022Zepben.Protobuf.HC'
  _SYF_INSTALLEDTXCAPACITYENTRY._options = None
  _SYF_INSTALLEDTXCAPACITYENTRY._serialized_options = b'8\001'
  _SYF._serialized_start=98
  _SYF._serialized_end=434
  _SYF_INSTALLEDTXCAPACITYENTRY._serialized_start=376
  _SYF_INSTALLEDTXCAPACITYENTRY._serialized_end=434
# @@protoc_insertion_point(module_scope)
