from .container import uSwidContainer as uSwidContainer

class uSwidFormatBase:
    def __init__(self) -> None: ...
    def load(self, blob: bytes) -> uSwidContainer: ...
    def save(self, container: uSwidContainer) -> bytes: ...
