# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61970/base/core/Feeder.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61970.base.core import EquipmentContainer_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_EquipmentContainer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3zepben/protobuf/cim/iec61970/base/core/Feeder.proto\x12&zepben.protobuf.cim.iec61970.base.core\x1a?zepben/protobuf/cim/iec61970/base/core/EquipmentContainer.proto\"\xbe\x01\n\x06\x46\x65\x65\x64\x65r\x12\x46\n\x02\x65\x63\x18\x01 \x01(\x0b\x32:.zepben.protobuf.cim.iec61970.base.core.EquipmentContainer\x12\x1e\n\x16normalHeadTerminalMRID\x18\x02 \x01(\t\x12&\n\x1enormalEnergizingSubstationMRID\x18\x03 \x01(\t\x12$\n\x1cnormalEnergizedLvFeederMRIDs\x18\x04 \x03(\tBW\n*com.zepben.protobuf.cim.iec61970.base.coreP\x01\xaa\x02&Zepben.Protobuf.CIM.IEC61970.Base.Coreb\x06proto3')



_FEEDER = DESCRIPTOR.message_types_by_name['Feeder']
Feeder = _reflection.GeneratedProtocolMessageType('Feeder', (_message.Message,), {
  'DESCRIPTOR' : _FEEDER,
  '__module__' : 'zepben.protobuf.cim.iec61970.base.core.Feeder_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.cim.iec61970.base.core.Feeder)
  })
_sym_db.RegisterMessage(Feeder)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.zepben.protobuf.cim.iec61970.base.coreP\001\252\002&Zepben.Protobuf.CIM.IEC61970.Base.Core'
  _FEEDER._serialized_start=161
  _FEEDER._serialized_end=351
# @@protoc_insertion_point(module_scope)
