"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""


from keras_core.src.backend.common.global_state import clear_session
from keras_core.src.backend.common.keras_tensor import is_keras_tensor
from keras_core.src.layers.preprocessing.feature_space import FeatureSpace
from keras_core.src.ops.operation_utils import get_source_inputs
from keras_core.src.saving.object_registration import CustomObjectScope
from keras_core.src.saving.object_registration import CustomObjectScope as custom_object_scope
from keras_core.src.saving.object_registration import get_custom_objects
from keras_core.src.saving.object_registration import get_registered_name
from keras_core.src.saving.object_registration import get_registered_object
from keras_core.src.saving.object_registration import register_keras_serializable
from keras_core.src.saving.serialization_lib import deserialize_keras_object
from keras_core.src.saving.serialization_lib import serialize_keras_object
from keras_core.src.trainers.data_adapters.data_adapter_utils import pack_x_y_sample_weight
from keras_core.src.trainers.data_adapters.data_adapter_utils import unpack_x_y_sample_weight
from keras_core.src.trainers.data_adapters.py_dataset_adapter import PyDataset
from keras_core.src.trainers.data_adapters.py_dataset_adapter import PyDataset as Sequence
from keras_core.src.utils.audio_dataset_utils import audio_dataset_from_directory
from keras_core.src.utils.dataset_utils import split_dataset
from keras_core.src.utils.file_utils import get_file
from keras_core.src.utils.image_dataset_utils import image_dataset_from_directory
from keras_core.src.utils.image_utils import array_to_img
from keras_core.src.utils.image_utils import img_to_array
from keras_core.src.utils.image_utils import load_img
from keras_core.src.utils.image_utils import save_img
from keras_core.src.utils.io_utils import disable_interactive_logging
from keras_core.src.utils.io_utils import enable_interactive_logging
from keras_core.src.utils.io_utils import is_interactive_logging_enabled
from keras_core.src.utils.model_visualization import model_to_dot
from keras_core.src.utils.model_visualization import plot_model
from keras_core.src.utils.numerical_utils import normalize
from keras_core.src.utils.numerical_utils import to_categorical
from keras_core.src.utils.progbar import Progbar
from keras_core.src.utils.rng_utils import set_random_seed
from keras_core.src.utils.sequence_utils import pad_sequences
from keras_core.src.utils.text_dataset_utils import text_dataset_from_directory
from keras_core.src.utils.timeseries_dataset_utils import timeseries_dataset_from_array
from keras_core.utils import legacy
