OPERATORS = {
    'is greater than or equals to': ('≥', ' >= '),
    'is greater than or equal to': ('≥', ' >= '),
    'is less than or equals to': ('≤', '<='),
    'is greater than equals to': ('≥', ' >= '),
    'is less than or equal to': ('≤', '<='),
    'is greater than equal to': ('≥', ' >= '),
    'is less than equals to': ('≤', '<='),
    'greater than equals to': ('≥', ' >= '),
    'is less than equal to': ('≤', '<='),
    'greater than equal to': ('≥', ' >= '),
    'less than equals to': ('≤', '<='),
    'less than equal to': ('≤', '<='),
    'is not equal to': ('≠', '!='),
    'is greater than': ('>', '>'),
    'square root of': ('√', '**0.5'),
    'is not equals': ('≠', '!='),
    'is not equal': ('≠', '!='),
    'multiplied by': ('*', '*'),
    'multiplied bi': ('*', '*'),
    'not equal to': ('≠', '!='),
    'greater than': ('>', '>'),
    'is less than': ('<', '<'),
    'is equal to': ('=', '=='),
    'per cent of': ('%', '/100 *'),
    'percent of': ('%', '/100 *'),
    'divided by': ('/', '/'),
    'equals to': ('=', '=='),
    'less than': ('<', '<'),
    'multiply': ('*', '*'),
    'equal to': ('=', '=='),
    'per cent': ('%', '/100'),
    'percent': ('%', '/100'),
    "square of": ('²', '**2'),
    'equals': ('=', '=='),
    'divide': ('/', '/'),
    'equal': ('=', '=='),
    'minus': ('-', '-'),
    'point': ('.', '.'),
    'plus': ('+', '+'),
}

