"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from docutils import nodes
from sphinx.builders.html import HTML5Translator

"""Utility functions for math."""
if TYPE_CHECKING:
    ...
def get_node_equation_number(writer: HTML5Translator, node: nodes.math_block) -> str:
    ...

def wrap_displaymath(text: str, label: str | None, numbering: bool) -> str:
    ...

