# Generated by Django 4.0 on 2022-11-04 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceunit',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.month'),
        ),
        migrations.AlterField(
            model_name='attendanceunit',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.year'),
        ),
    ]
