
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-09-20T11:36:14+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "49a4eedfc90e8427168511ffc06d676245687d95",
 "version": "2.11.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
