# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult',
    'AwaitableGetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult',
    'get_queuing_qos_policy_map_match_class_map_remaining_bandwidth',
    'get_queuing_qos_policy_map_match_class_map_remaining_bandwidth_output',
]

@pulumi.output_type
class GetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult:
    """
    A collection of values returned by getQueuingQosPolicyMapMatchClassMapRemainingBandwidth.
    """
    def __init__(__self__, class_map_name=None, device=None, id=None, policy_map_name=None, value=None):
        if class_map_name and not isinstance(class_map_name, str):
            raise TypeError("Expected argument 'class_map_name' to be a str")
        pulumi.set(__self__, "class_map_name", class_map_name)
        if device and not isinstance(device, str):
            raise TypeError("Expected argument 'device' to be a str")
        pulumi.set(__self__, "device", device)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if policy_map_name and not isinstance(policy_map_name, str):
            raise TypeError("Expected argument 'policy_map_name' to be a str")
        pulumi.set(__self__, "policy_map_name", policy_map_name)
        if value and not isinstance(value, int):
            raise TypeError("Expected argument 'value' to be a int")
        pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter(name="classMapName")
    def class_map_name(self) -> str:
        return pulumi.get(self, "class_map_name")

    @property
    @pulumi.getter
    def device(self) -> Optional[str]:
        return pulumi.get(self, "device")

    @property
    @pulumi.getter
    def id(self) -> str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="policyMapName")
    def policy_map_name(self) -> str:
        return pulumi.get(self, "policy_map_name")

    @property
    @pulumi.getter
    def value(self) -> int:
        return pulumi.get(self, "value")


class AwaitableGetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult(GetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult(
            class_map_name=self.class_map_name,
            device=self.device,
            id=self.id,
            policy_map_name=self.policy_map_name,
            value=self.value)


def get_queuing_qos_policy_map_match_class_map_remaining_bandwidth(class_map_name: Optional[str] = None,
                                                                   device: Optional[str] = None,
                                                                   policy_map_name: Optional[str] = None,
                                                                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['classMapName'] = class_map_name
    __args__['device'] = device
    __args__['policyMapName'] = policy_map_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nxos:nxos/getQueuingQosPolicyMapMatchClassMapRemainingBandwidth:getQueuingQosPolicyMapMatchClassMapRemainingBandwidth', __args__, opts=opts, typ=GetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult).value

    return AwaitableGetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult(
        class_map_name=pulumi.get(__ret__, 'class_map_name'),
        device=pulumi.get(__ret__, 'device'),
        id=pulumi.get(__ret__, 'id'),
        policy_map_name=pulumi.get(__ret__, 'policy_map_name'),
        value=pulumi.get(__ret__, 'value'))


@_utilities.lift_output_func(get_queuing_qos_policy_map_match_class_map_remaining_bandwidth)
def get_queuing_qos_policy_map_match_class_map_remaining_bandwidth_output(class_map_name: Optional[pulumi.Input[str]] = None,
                                                                          device: Optional[pulumi.Input[Optional[str]]] = None,
                                                                          policy_map_name: Optional[pulumi.Input[str]] = None,
                                                                          opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetQueuingQosPolicyMapMatchClassMapRemainingBandwidthResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
