# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetSubinterfaceVrfResult',
    'AwaitableGetSubinterfaceVrfResult',
    'get_subinterface_vrf',
    'get_subinterface_vrf_output',
]

@pulumi.output_type
class GetSubinterfaceVrfResult:
    """
    A collection of values returned by getSubinterfaceVrf.
    """
    def __init__(__self__, device=None, id=None, interface_id=None, vrf_dn=None):
        if device and not isinstance(device, str):
            raise TypeError("Expected argument 'device' to be a str")
        pulumi.set(__self__, "device", device)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if interface_id and not isinstance(interface_id, str):
            raise TypeError("Expected argument 'interface_id' to be a str")
        pulumi.set(__self__, "interface_id", interface_id)
        if vrf_dn and not isinstance(vrf_dn, str):
            raise TypeError("Expected argument 'vrf_dn' to be a str")
        pulumi.set(__self__, "vrf_dn", vrf_dn)

    @property
    @pulumi.getter
    def device(self) -> Optional[str]:
        return pulumi.get(self, "device")

    @property
    @pulumi.getter
    def id(self) -> str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="interfaceId")
    def interface_id(self) -> str:
        return pulumi.get(self, "interface_id")

    @property
    @pulumi.getter(name="vrfDn")
    def vrf_dn(self) -> str:
        return pulumi.get(self, "vrf_dn")


class AwaitableGetSubinterfaceVrfResult(GetSubinterfaceVrfResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSubinterfaceVrfResult(
            device=self.device,
            id=self.id,
            interface_id=self.interface_id,
            vrf_dn=self.vrf_dn)


def get_subinterface_vrf(device: Optional[str] = None,
                         interface_id: Optional[str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSubinterfaceVrfResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['device'] = device
    __args__['interfaceId'] = interface_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nxos:nxos/getSubinterfaceVrf:getSubinterfaceVrf', __args__, opts=opts, typ=GetSubinterfaceVrfResult).value

    return AwaitableGetSubinterfaceVrfResult(
        device=pulumi.get(__ret__, 'device'),
        id=pulumi.get(__ret__, 'id'),
        interface_id=pulumi.get(__ret__, 'interface_id'),
        vrf_dn=pulumi.get(__ret__, 'vrf_dn'))


@_utilities.lift_output_func(get_subinterface_vrf)
def get_subinterface_vrf_output(device: Optional[pulumi.Input[Optional[str]]] = None,
                                interface_id: Optional[pulumi.Input[str]] = None,
                                opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetSubinterfaceVrfResult]:
    """
    Use this data source to access information about an existing resource.
    """
    ...
