# Generated by Django 2.2.19 on 2021-03-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_crontab_manager', '0003_auto_20210303_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='django_crontab_manager.Server', verbose_name='Server'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='success_determination_rule',
            field=models.IntegerField(choices=[(0, 'An 0 exit code is considered successful'), (10, 'Stdout contains given keyword is considered successful'), (20, 'Stdout NOT contains given keyword is considered successful'), (30, 'Stdout matchs the regex pattern is considered successful')], default=0, verbose_name='Success Determination Rule'),
        ),
    ]
