# Generated by Django 4.0 on 2022-11-04 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_month_attendance_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetotal',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.month'),
        ),
        migrations.AlterField(
            model_name='attendancetotal',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.year'),
        ),
    ]
