VERSION_YEAR = 2023
VERSION_MONTH = int('09')
VERSION_DAY = int('20')
VERSION_HOUR = int('01')
VERSION_MINUTE = int('56')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202309200156
version_date = '2023/09/20 01:56'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
