# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from benny_kubernetes.models.io_k8s_api_storage_v1_volume_node_resources import IoK8sApiStorageV1VolumeNodeResources  # noqa: E501

class TestIoK8sApiStorageV1VolumeNodeResources(unittest.TestCase):
    """IoK8sApiStorageV1VolumeNodeResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiStorageV1VolumeNodeResources:
        """Test IoK8sApiStorageV1VolumeNodeResources
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiStorageV1VolumeNodeResources`
        """
        model = IoK8sApiStorageV1VolumeNodeResources()  # noqa: E501
        if include_optional:
            return IoK8sApiStorageV1VolumeNodeResources(
                count = 56
            )
        else:
            return IoK8sApiStorageV1VolumeNodeResources(
        )
        """

    def testIoK8sApiStorageV1VolumeNodeResources(self):
        """Test IoK8sApiStorageV1VolumeNodeResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
