# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from benny_kubernetes.models.io_k8s_api_discovery_v1beta1_endpoint_port import IoK8sApiDiscoveryV1beta1EndpointPort  # noqa: E501

class TestIoK8sApiDiscoveryV1beta1EndpointPort(unittest.TestCase):
    """IoK8sApiDiscoveryV1beta1EndpointPort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiDiscoveryV1beta1EndpointPort:
        """Test IoK8sApiDiscoveryV1beta1EndpointPort
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiDiscoveryV1beta1EndpointPort`
        """
        model = IoK8sApiDiscoveryV1beta1EndpointPort()  # noqa: E501
        if include_optional:
            return IoK8sApiDiscoveryV1beta1EndpointPort(
                app_protocol = '',
                name = '',
                port = 56,
                protocol = ''
            )
        else:
            return IoK8sApiDiscoveryV1beta1EndpointPort(
        )
        """

    def testIoK8sApiDiscoveryV1beta1EndpointPort(self):
        """Test IoK8sApiDiscoveryV1beta1EndpointPort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
