# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from benny_kubernetes.models.io_k8s_api_core_v1_node_config_source import IoK8sApiCoreV1NodeConfigSource  # noqa: E501

class TestIoK8sApiCoreV1NodeConfigSource(unittest.TestCase):
    """IoK8sApiCoreV1NodeConfigSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCoreV1NodeConfigSource:
        """Test IoK8sApiCoreV1NodeConfigSource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCoreV1NodeConfigSource`
        """
        model = IoK8sApiCoreV1NodeConfigSource()  # noqa: E501
        if include_optional:
            return IoK8sApiCoreV1NodeConfigSource(
                config_map = benny_kubernetes.models.io/k8s/api/core/v1/config_map_node_config_source.io.k8s.api.core.v1.ConfigMapNodeConfigSource(
                    kubelet_config_key = '', 
                    name = '', 
                    namespace = '', 
                    resource_version = '', 
                    uid = '', )
            )
        else:
            return IoK8sApiCoreV1NodeConfigSource(
        )
        """

    def testIoK8sApiCoreV1NodeConfigSource(self):
        """Test IoK8sApiCoreV1NodeConfigSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
