# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from benny_kubernetes.models.io_k8s_api_certificates_v1beta1_certificate_signing_request_status import IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus  # noqa: E501

class TestIoK8sApiCertificatesV1beta1CertificateSigningRequestStatus(unittest.TestCase):
    """IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus:
        """Test IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus`
        """
        model = IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus()  # noqa: E501
        if include_optional:
            return IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus(
                certificate = 'YQ==',
                conditions = [
                    benny_kubernetes.models.io/k8s/api/certificates/v1beta1/certificate_signing_request_condition.io.k8s.api.certificates.v1beta1.CertificateSigningRequestCondition(
                        last_update_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        message = '', 
                        reason = '', 
                        type = '', )
                    ]
            )
        else:
            return IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus(
        )
        """

    def testIoK8sApiCertificatesV1beta1CertificateSigningRequestStatus(self):
        """Test IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
