"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-pe2x*8ooa=+di$^)*udwv2)m%a_6wk!u&e7d6-7u92&h#qrfhk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "sat_automations.gold_feed_automation",
    "sat_automations.disablement_automation",
    "sat_automations.housing_automation",
    "sat_automations.manage_automations",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "example.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

CELERY_BROKER = ("DUMMY",)
CELERY_BROKER_URL = ("DUMMY_URL",)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CLEARANCE_SERVICE_URL = os.getenv("CLEARANCE_SERVICE_URL")
PEOPLESOFT_PROXY_URL = os.getenv("PEOPLESOFT_PROXY_URL")
DUMMY_PEOPLESOFT_PROXY = os.getenv("DUMMY_PEOPLESOFT_PROXY", "TEST")
AUTH_SERVICE_URL = os.getenv("AUTH_SERVICE_URL")
PEOPLESOFT_ST_CONNECT_STR = os.getenv("PEOPLESOFT_ST_CONNECT_STR")
ORACLE_LIB_PATH = os.getenv("ORACLE_LIB_PATH")
CCURE_SERVER = os.getenv("CCURE_SERVER")
CCURE_DB = os.getenv("CCURE_DB")
CCURE_PORT = os.getenv("CCURE_PORT")
CCURE_USERNAME = os.getenv("CCURE_USERNAME")
CCURE_PASSWORD = os.getenv("CCURE_PASSWORD")

# Feed DB
FEED_SERVER = os.getenv("FEED_SERVER")
FEED_PORT = os.getenv("FEED_PORT")
FEED_USERNAME = os.getenv("FEED_USERNAME")
FEED_PASSWORD = os.getenv("FEED_PASSWORD")

# Gold Feed
GOLD_DB_DSN = os.getenv("GOLD_DB_DSN")
GOLD_DB_USERNAME = os.getenv("GOLD_DB_USERNAME")
GOLD_DB_PASSWORD = os.getenv("GOLD_DB_PASSWORD")

# PRTG
GOLD_PRTG_GUID = os.getenv("GOLD_PRTG_GUID")
GOLD_PRTG_BASE_URL = os.getenv("GOLD_PRTG_BASE_URL")
