from ._exception import ScriptCompilerException as ScriptCompilerException
from .content import Content as Content
from .naming import Naming as Naming
from typing import Any, Final

class Processor:
    SCRIPTS_FILE_EXTENSION: Final[str]
    def __init__(self) -> None: ...
    def get_id(self) -> int: ...
    def get_language(self) -> str: ...
    def get_output(self) -> dict[str, dict[str, dict[str, Any]]]: ...
    def process(self, _path: str) -> None: ...
