# coding: utf-8

"""
    VRt.Studio [ST]

    The version of the OpenAPI document: 6.14.2133

    Generated by OpenAPI Generator: 6.6.0

    Do not edit the code manually

    2023 Veeroute
"""


from inspect import getfullargspec
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TableHardlinkColumnType(str, Enum):
    """
    Hardlink table column name. 
    """

    """
    allowed enum values
    """
    ESSENCE_KEY = 'ESSENCE_KEY'
    ENABLED = 'ENABLED'
    PRISTINE = 'PRISTINE'
    ELEMENT_TYPE = 'ELEMENT_TYPE'
    ELEMENTS_COUNT = 'ELEMENTS_COUNT'
    TRIP_KEY = 'TRIP_KEY'
    TRIP_NAME = 'TRIP_NAME'

