# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61970/base/meas/MeasurementValue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=zepben/protobuf/cim/iec61970/base/meas/MeasurementValue.proto\x12&zepben.protobuf.cim.iec61970.base.meas\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n\x10MeasurementValue\x12-\n\ttimeStamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampBW\n*com.zepben.protobuf.cim.iec61970.base.measP\x01\xaa\x02&Zepben.Protobuf.CIM.IEC61970.Base.Measb\x06proto3')



_MEASUREMENTVALUE = DESCRIPTOR.message_types_by_name['MeasurementValue']
MeasurementValue = _reflection.GeneratedProtocolMessageType('MeasurementValue', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTVALUE,
  '__module__' : 'zepben.protobuf.cim.iec61970.base.meas.MeasurementValue_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.cim.iec61970.base.meas.MeasurementValue)
  })
_sym_db.RegisterMessage(MeasurementValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n*com.zepben.protobuf.cim.iec61970.base.measP\001\252\002&Zepben.Protobuf.CIM.IEC61970.Base.Meas'
  _MEASUREMENTVALUE._serialized_start=138
  _MEASUREMENTVALUE._serialized_end=203
# @@protoc_insertion_point(module_scope)
