from django.conf import settings

CLEARANCE_BASE_URL = settings.CLEARANCE_SERVICE_URL
PEOPLESOFT_ST_CONNECT_STR = settings.PEOPLESOFT_ST_CONNECT_STR
AUTH_SERVICE_URL = settings.AUTH_SERVICE_URL
ORACLE_LIB_PATH = settings.ORACLE_LIB_PATH
CCURE_SERVER = settings.CCURE_SERVER
CCURE_DB = settings.CCURE_DB
CCURE_USERNAME = settings.CCURE_USERNAME
CCURE_PASSWORD = settings.CCURE_PASSWORD

