SELECT  REF_COLUMN_NAME as COLUMN_NAME,
        REF_DATABASE_NAME || '.' || REF_SCHEMA_NAME || '.' || REF_ENTITY_NAME AS MODEL,
        REF_ENTITY_DOMAIN as MATERIALIZATION
FROM    TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => %s));
