# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt

class IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig(BaseModel):
    """
    WebhookThrottleConfig holds the configuration for throttling events  # noqa: E501
    """
    burst: Optional[StrictInt] = Field(None, description="ThrottleBurst is the maximum number of events sent at the same moment default 15 QPS")
    qps: Optional[StrictInt] = Field(None, description="ThrottleQPS maximum number of batches per second default 10 QPS")
    __properties = ["burst", "qps"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig:
        """Create an instance of IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig:
        """Create an instance of IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig.parse_obj(obj)

        _obj = IoK8sApiAuditregistrationV1alpha1WebhookThrottleConfig.parse_obj({
            "burst": obj.get("burst"),
            "qps": obj.get("qps")
        })
        return _obj


