# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: caerep.coordinate_system.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from caerep import common_pb2 as caerep_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63\x61\x65rep.coordinate_system.proto\x12%ans.protocol.caerep.coordinate_system\x1a\x13\x63\x61\x65rep.common.proto\"K\n\x04Type\"C\n\x04\x45num\x12\r\n\tCARTESIAN\x10\x00\x12\x0f\n\x0b\x43YLINDRICAL\x10\x01\x12\r\n\tSPHERICAL\x10\x02\x12\x0c\n\x08TOROIDAL\x10\x03\"\x9d\x01\n\tMatrix3X3\x12\x12\n\northogonal\x18\x01 \x01(\x08\x12\x0c\n\x04x1y1\x18\x02 \x01(\x01\x12\x0c\n\x04x2y1\x18\x03 \x01(\x01\x12\x0c\n\x04x3y1\x18\x04 \x01(\x01\x12\x0c\n\x04x1y2\x18\x05 \x01(\x01\x12\x0c\n\x04x2y2\x18\x06 \x01(\x01\x12\x0c\n\x04x3y2\x18\x07 \x01(\x01\x12\x0c\n\x04x1y3\x18\x08 \x01(\x01\x12\x0c\n\x04x2y3\x18\t \x01(\x01\x12\x0c\n\x04x3y3\x18\n \x01(\x01\"\xb5\x03\n\x10\x43oordinateSystem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63\x61ption\x18\x02 \x01(\t\x12\x11\n\tis_global\x18\x03 \x01(\x08\x12\x0e\n\x06param1\x18\x04 \x01(\x01\x12\x0e\n\x06param2\x18\x05 \x01(\x01\x12\x14\n\x0csingularity1\x18\x06 \x01(\x05\x12\x14\n\x0csingularity2\x18\x07 \x01(\x05\x12\x1b\n\x13solver_coord_number\x18\x08 \x01(\x05\x12>\n\x04type\x18\t \x01(\x0e\x32\x30.ans.protocol.caerep.coordinate_system.Type.Enum\x12\x45\n\x0borientation\x18\n \x01(\x0b\x32\x30.ans.protocol.caerep.coordinate_system.Matrix3X3\x12\x33\n\x06origin\x18\x0b \x01(\x0b\x32#.ans.protocol.caerep.common.Point3D\x12\x16\n\x0esend_to_solver\x18\x0c \x01(\x08\x12\x13\n\x0bsolver_name\x18\r \x01(\t\x12\x1f\n\x17\x63oordinate_system_index\x18\x0e \x01(\x05\x42)H\x03\xaa\x02$Ans.Protocol.CAERep.CoordinateSystemb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'caerep.coordinate_system_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003\252\002$Ans.Protocol.CAERep.CoordinateSystem'
  _TYPE._serialized_start=94
  _TYPE._serialized_end=169
  _TYPE_ENUM._serialized_start=102
  _TYPE_ENUM._serialized_end=169
  _MATRIX3X3._serialized_start=172
  _MATRIX3X3._serialized_end=329
  _COORDINATESYSTEM._serialized_start=332
  _COORDINATESYSTEM._serialized_end=769
# @@protoc_insertion_point(module_scope)
