# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: caerep.remote_point.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import quantity_pb2 as common_dot_quantity__pb2
from caerep import common_pb2 as caerep_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63\x61\x65rep.remote_point.proto\x12 ans.protocol.caerep.remote_point\x1a\x15\x63ommon.quantity.proto\x1a\x13\x63\x61\x65rep.common.proto\"=\n\x04Type\"5\n\x04\x45num\x12\r\n\tCARTESIAN\x10\x00\x12\x0f\n\x0b\x43YLINDRICAL\x10\x01\x12\r\n\tSPHERICAL\x10\x02\"9\n\x0b\x44ofMaskType\"*\n\x04\x45num\x12\x16\n\x12PROGRAM_CONTROLLED\x10\x00\x12\n\n\x06MANUAL\x10\x01\"D\n\x08\x42\x65havior\"8\n\x04\x45num\x12\t\n\x05RIGID\x10\x00\x12\x0e\n\nDEFORMABLE\x10\x01\x12\x08\n\x04\x42\x45\x41M\x10\x02\x12\x0b\n\x07\x43OUPLED\x10\x03\"\x80\x05\n\x0bRemotePoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63\x61ption\x18\x02 \x01(\t\x12\x1a\n\x12\x62\x65\x61m_material_name\x18\x04 \x01(\t\x12\x19\n\x11\x63ondensed_part_id\x18\x05 \x01(\x05\x12\x10\n\x08\x64of_mask\x18\x06 \x01(\r\x12I\n\rdof_mask_type\x18\x07 \x01(\x0e\x32\x32.ans.protocol.caerep.remote_point.DofMaskType.Enum\x12\x13\n\x0bhas_scoping\x18\x08 \x01(\x08\x12\x46\n\rload_behavior\x18\t \x01(\x0e\x32/.ans.protocol.caerep.remote_point.Behavior.Enum\x12\x35\n\x08location\x18\n \x01(\x0b\x32#.ans.protocol.caerep.common.Point3D\x12\x19\n\x11node_reference_id\x18\x0b \x01(\x05\x12\x11\n\tparent_id\x18\x0c \x01(\x05\x12\x13\n\x0bparent_name\x18\r \x01(\t\x12\x10\n\x08part_ids\x18\x0e \x03(\x05\x12<\n\x0cpinball_size\x18\x0f \x01(\x0b\x32&.ans.protocol.common.quantity.Quantity\x12\x36\n\x06radius\x18\x10 \x01(\x0b\x32&.ans.protocol.common.quantity.Quantity\x12\x18\n\x10ref_coord_sys_id\x18\x11 \x01(\x05\x12\x0f\n\x07scoping\x18\x12 \x03(\x05\x12\x1f\n\x17used_for_direct_scoping\x18\x13 \x01(\x08\x12\x15\n\rfree_standing\x18\x14 \x01(\x08\x42$H\x03\xaa\x02\x1f\x41ns.Protocol.CAERep.RemotePointb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'caerep.remote_point_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003\252\002\037Ans.Protocol.CAERep.RemotePoint'
  _TYPE._serialized_start=107
  _TYPE._serialized_end=168
  _TYPE_ENUM._serialized_start=115
  _TYPE_ENUM._serialized_end=168
  _DOFMASKTYPE._serialized_start=170
  _DOFMASKTYPE._serialized_end=227
  _DOFMASKTYPE_ENUM._serialized_start=185
  _DOFMASKTYPE_ENUM._serialized_end=227
  _BEHAVIOR._serialized_start=229
  _BEHAVIOR._serialized_end=297
  _BEHAVIOR_ENUM._serialized_start=241
  _BEHAVIOR_ENUM._serialized_end=297
  _REMOTEPOINT._serialized_start=300
  _REMOTEPOINT._serialized_end=940
# @@protoc_insertion_point(module_scope)
