# coding: utf-8

"""
    Ostatní dokumenty CITES

    Toto je API pro Domino konektor ostatních dokumentů CITES  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import citesdoc
from citesdoc.models.template_type import TemplateType  # noqa: E501
from citesdoc.rest import ApiException


class TestTemplateType(unittest.TestCase):
    """TemplateType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplateType(self):
        """Test TemplateType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = citesdoc.models.template_type.TemplateType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
