# Generated by Django 4.1.9 on 2023-06-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_all_in_one_accessibility",
            "0005_wagtail_all_in_one_accessibility_aioa_icon_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_icon_size",
            field=models.CharField(
                choices=[
                    ("singleline", "Single line text"),
                    ("multiline", "Multi-line text"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("url", "URL"),
                    ("checkbox", "Checkbox"),
                    ("checkboxes", "Checkboxes"),
                    ("dropdown", "Drop down"),
                    ("multiselect", "Multiple select"),
                    ("radio", "Radio buttons"),
                    ("date", "Date"),
                    ("datetime", "Date/time"),
                    ("hidden", "Hidden field"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
