# Generated by Django 4.1.9 on 2023-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_all_in_one_accessibility",
            "0009_alter_wagtail_all_in_one_accessibility_aioa_icon_size",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_icon_size",
            field=models.CharField(
                help_text='<script>alert("I am an alert box!");</script>',
                max_length=200,
                null=True,
            ),
        ),
    ]
