# Generated by Django 4.1.9 on 2023-06-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_all_in_one_accessibility",
            "0011_wagtail_all_in_one_accessibility_aioa_text_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_text",
            field=models.CharField(
                help_text='<script>const sizeOptions = document.querySelectorAll(\'input[name="aioa_icon_size"]\');\n                const sizeOptionsImg = document.querySelectorAll(\'input[name="aioa_icon_size"] + img\');\n                const typeOptions = document.querySelectorAll(\'input[name="aioa_icon_type"]\');\n                typeOptions.forEach(option => {\n                    option.addEventListener("click", (event) => {\n                        sizeOptionsImg.forEach(option2 => {\n                            var ico_type = document.querySelector(\'input[name="aioa_icon_type"]:checked\').value;\n                            option2.setAttribute("src", "https://skynettechnologies.com/sites/default/files/python/" + ico_type + ".svg");\n                        });\n                    });\n                });</script>',
                max_length=200,
                null=True,
            ),
        ),
    ]
