# Generated by Django 4.2 on 2023-07-14 12:17

from django.db import migrations, models
import wagtail_all_in_one_accessibility.db


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_all_in_one_accessibility",
            "0026_alter_wagtail_all_in_one_accessibility_aioa_icon_size_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_text",
            field=models.CharField(
                blank=True,
                help_text='<script>const sizeOptions = document.querySelectorAll(\'input[name="aioa_icon_size_0"]\');\n                const sizeOptionsImg = document.querySelectorAll(\'input[name="aioa_icon_size_0"] + img\');\n                const typeOptions = document.querySelectorAll(\'input[name="aioa_icon_type_0"]\');\n                typeOptions.forEach(option => {\n                    option.addEventListener("click", (event) => {\n                        sizeOptionsImg.forEach(option2 => {\n                            var ico_type = document.querySelector(\'input[name="aioa_icon_type_0"]:checked\').value;\n                            option2.setAttribute("src", "https://skynettechnologies.com/sites/default/files/python/" + ico_type + ".svg");\n                        });\n                    });\n                });</script>',
                max_length=200,
                null=True,
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_icon_size",
            field=wagtail_all_in_one_accessibility.db.RadioGridField(
                default=[
                    (
                        "aioa-default-icon",
                        '<img class="csticontype" src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="55" height="55" />',
                    )
                ],
                help_text='<script>const sizeOptions = document.querySelectorAll(\'input[name="aioa_icon_size_0"]\');\n                const sizeOptionsImg = document.querySelectorAll(\'input[name="aioa_icon_size_0"] + img\');\n                const typeOptions = document.querySelectorAll(\'input[name="aioa_icon_type_0"]\');\n                typeOptions.forEach(option => {\n                    option.addEventListener("click", (event) => {\n                        sizeOptionsImg.forEach(option2 => {\n                            var ico_type = document.querySelector(\'input[name="aioa_icon_type_0"]:checked\').value;\n                            option2.setAttribute("src", "https://skynettechnologies.com/sites/default/files/python/" + ico_type + ".svg");\n                        });\n                    });\n                });</script>',
                require_all_fields=True,
                rows=((1, ""),),
                values=[
                    (
                        "aioa-big-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="75" height="75" />',
                    ),
                    (
                        "aioa-medium-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />',
                    ),
                    (
                        "aioa-default-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="55" height="55" />',
                    ),
                    (
                        "aioa-small-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="45" height="45" />',
                    ),
                    (
                        "aioa-extra-small-icon",
                        '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="35" height="35"/>',
                    ),
                ],
                verbose_name="Icon Size For Desktop",
            ),
        ),
    ]
