# Generated by Django 4.2 on 2023-07-14 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_all_in_one_accessibility",
            "0027_wagtail_all_in_one_accessibility_aioa_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_text",
        ),
    ]
