# Generated by Django 4.2 on 2023-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_all_in_one_accessibility",
            "0028_remove_wagtail_all_in_one_accessibility_aioa_text",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_text",
            field=models.CharField(
                blank=True,
                help_text='<script>const sizeOptions = document.querySelectorAll(\'input[name="aioa_icon_size"]\');\n                const sizeOptionsImg = document.querySelectorAll(\'input[name="aioa_icon_size"] + img\');\n                const typeOptions = document.querySelectorAll(\'input[name="aioa_icon_type"]\');\n                typeOptions.forEach(option => {\n                    option.addEventListener("click", (event) => {\n                        sizeOptionsImg.forEach(option2 => {\n                            var ico_type = document.querySelector(\'input[name="aioa_icon_type"]:checked\').value;\n                            option2.setAttribute("src", "https://skynettechnologies.com/sites/default/files/python/" + ico_type + ".svg");\n                        });\n                    });\n                });</script>',
                max_length=200,
                null=True,
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_icon_size",
            field=models.CharField(
                default=(
                    "aioa-medium-icon",
                    '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-1.svg" width="65" height="65" />',
                ),
                max_length=200,
                null=True,
                verbose_name="Icon Size",
            ),
        ),
        migrations.AlterField(
            model_name="wagtail_all_in_one_accessibility",
            name="aioa_icon_type",
            field=models.CharField(
                default=(
                    "aioa-icon-type-1",
                    '<img src="https://skynettechnologies.com/sites/default/files/python/aioa-icon-type-2.svg" width="65" height="65" />',
                ),
                max_length=200,
                null=True,
                verbose_name="Icon Type",
            ),
        ),
    ]
