# coding: utf-8

"""
    Synctera API

    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>  # noqa: E501

    The version of the OpenAPI document: 1.41.3
    Contact: dev@swadesh.co
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TransferType(str, Enum):
    """
    Type of operation for transfer.  Type | Description --- | --- PUSH | Push fund to the external card from the account_id PULL | Pull funds from the external card to the account_id PULL_REVERSAL | Reversed pull funds transfer from an external card 
    """

    """
    allowed enum values
    """
    PULL = 'PULL'
    PULL_REVERSAL = 'PULL_REVERSAL'
    PUSH = 'PUSH'

    @classmethod
    def from_json(cls, json_str: str) -> TransferType:
        """Create an instance of TransferType from a JSON string"""
        return TransferType(json.loads(json_str))


