import datetime

DATE_FMT = "%Y-%m-%d %H:%M:%S"

FAKE_GOLD_DATA = [
    {
        "PatronID": 734424,
        "CampusID": "200408152",
        "FirstName": "Julian",
        "MiddleName": "",
        "LastName": "Gomez",
        "Classification": "SO",
        "Email": "jgomez5@ncsu.edu",
        "Type": "EDIT",
        "Department": "Scholarships & Financial Aid",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358422",
        "CIDC": "200408152:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:17:16", DATE_FMT),
    },
    {
        "PatronID": 734424,
        "CampusID": "200408152",
        "FirstName": "Julian",
        "MiddleName": "",
        "LastName": "Gomez",
        "Classification": "SO",
        "Email": "jgomez5@ncsu.edu",
        "Type": "CARD",
        "Department": "Scholarships & Financial Aid",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358422",
        "CIDC": "200408152:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:14:20", DATE_FMT),
    },
    {
        "PatronID": 190732,
        "CampusID": "000834927",
        "FirstName": "Kathryn",
        "MiddleName": "Marie",
        "LastName": "Asad",
        "Classification": "EPA",
        "Email": "kmasad@ncsu.edu",
        "Type": "EDIT",
        "Department": "Graphic & Industrial Design",
        "PersonnelType": "FACULTY/STAFF",
        "ProxCardID": "0356330",
        "CIDC": "000834927:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:14:12", DATE_FMT),
    },
    {
        "PatronID": 190732,
        "CampusID": "000834927",
        "FirstName": "Kathryn",
        "MiddleName": "Marie",
        "LastName": "Asad",
        "Classification": "EPA",
        "Email": "kmasad@ncsu.edu",
        "Type": "CARD",
        "Department": "Graphic & Industrial Design",
        "PersonnelType": "FACULTY/STAFF",
        "ProxCardID": "0356330",
        "CIDC": "000834927:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:10:56", DATE_FMT),
    },
    {
        "PatronID": 737653,
        "CampusID": "200400417",
        "FirstName": "Madison",
        "MiddleName": "K",
        "LastName": "Minihan",
        "Classification": "JR",
        "Email": "mkminiha@ncsu.edu",
        "Type": "EDIT",
        "Department": "Textiles-Dean's Office",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358535",
        "CIDC": "200400417:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:13:58", DATE_FMT),
    },
    {
        "PatronID": 745087,
        "CampusID": "200435798",
        "FirstName": "Ailey",
        "MiddleName": "",
        "LastName": "O'Toole",
        "Classification": "SR",
        "Email": "aotoole@ncsu.edu",
        "Type": "EDIT",
        "Department": "",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358421",
        "CIDC": "200435798:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:12:19", DATE_FMT),
    },
    {
        "PatronID": 737653,
        "CampusID": "200400417",
        "FirstName": "Madison",
        "MiddleName": "K",
        "LastName": "Minihan",
        "Classification": "JR",
        "Email": "mkminiha@ncsu.edu",
        "Type": "CARD",
        "Department": "Textiles-Dean's Office",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358535",
        "CIDC": "200400417:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:10:46", DATE_FMT),
    },
    {
        "PatronID": 745087,
        "CampusID": "200435798",
        "FirstName": "Ailey",
        "MiddleName": "",
        "LastName": "O'Toole",
        "Classification": "SR",
        "Email": "aotoole@ncsu.edu",
        "Type": "CARD",
        "Department": "",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358421",
        "CIDC": "200435798:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:09:44", DATE_FMT),
    },
    {
        "PatronID": 794188,
        "CampusID": "200557867",
        "FirstName": "Yun",
        "MiddleName": "",
        "LastName": "Mao",
        "Classification": "GR",
        "Email": "ymao8@ncsu.edu",
        "Type": "CARD",
        "Department": "Dept-Population,Health,Pathobi",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358420",
        "CIDC": "200557867:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:06:02", DATE_FMT),
    },
    {
        "PatronID": 794758,
        "CampusID": "001136742",
        "FirstName": "Kimberly",
        "MiddleName": "Berg",
        "LastName": "Farnsworth",
        "Classification": "EPA",
        "Email": "kbfarnsw@ncsu.edu",
        "Type": "CARD",
        "Department": "Friday Institute",
        "PersonnelType": "FACULTY/STAFF",
        "ProxCardID": "0356329",
        "CIDC": "001136742:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 13:01:41", DATE_FMT),
    },
    {
        "PatronID": 794755,
        "CampusID": "001136680",
        "FirstName": "Larry",
        "MiddleName": "",
        "LastName": "Dixon",
        "Classification": "EPA",
        "Email": "ldixon3@ncsu.edu",
        "Type": "CARD",
        "Department": "Men's Basketball",
        "PersonnelType": "FACULTY/STAFF",
        "ProxCardID": "0356328",
        "CIDC": "001136680:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 12:59:11", DATE_FMT),
    },
    {
        "PatronID": 769747,
        "CampusID": "001133385",
        "FirstName": "Kristen",
        "MiddleName": "Taylor",
        "LastName": "Culbreath",
        "Classification": "TMP",
        "Email": "kculbre2@ncsu.edu",
        "Type": "EDIT",
        "Department": "DELTA Marketing",
        "PersonnelType": "TEMPORARY EMPLOYEE",
        "ProxCardID": "0358534",
        "CIDC": "001133385:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 12:54:48", DATE_FMT),
    },
    {
        "PatronID": 769747,
        "CampusID": "001133385",
        "FirstName": "Kristen",
        "MiddleName": "Taylor",
        "LastName": "Culbreath",
        "Classification": "TMP",
        "Email": "kculbre2@ncsu.edu",
        "Type": "CARD",
        "Department": "DELTA Marketing",
        "PersonnelType": "TEMPORARY EMPLOYEE",
        "ProxCardID": "0358534",
        "CIDC": "001133385:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 12:51:40", DATE_FMT),
    },
    {
        "PatronID": 730561,
        "CampusID": "200393400",
        "FirstName": "Naser",
        "MiddleName": "Mamoun",
        "LastName": "Issa",
        "Classification": "SR",
        "Email": "nmissa2@ncsu.edu",
        "Type": "EDIT",
        "Department": "Lab for Analytic Sciences",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358533",
        "CIDC": "200393400:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 12:50:52", DATE_FMT),
    },
    {
        "PatronID": 659310,
        "CampusID": "200075736",
        "FirstName": "Jessica",
        "MiddleName": "Lynn",
        "LastName": "Wadsack-Stewart",
        "Classification": "GR",
        "Email": "jlwadsac@ncsu.edu",
        "Type": "EDIT",
        "Department": "Acad Sup Prog For Stu Athl",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358419",
        "CIDC": "200075736:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 12:49:50", DATE_FMT),
    },
    {
        "PatronID": 730561,
        "CampusID": "200393400",
        "FirstName": "Naser",
        "MiddleName": "Mamoun",
        "LastName": "Issa",
        "Classification": "SR",
        "Email": "nmissa2@ncsu.edu",
        "Type": "CARD",
        "Department": "Lab for Analytic Sciences",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358533",
        "CIDC": "200393400:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 12:47:32", DATE_FMT),
    },
    {
        "PatronID": 659310,
        "CampusID": "200075736",
        "FirstName": "Jessica",
        "MiddleName": "Lynn",
        "LastName": "Wadsack-Stewart",
        "Classification": "GR",
        "Email": "jlwadsac@ncsu.edu",
        "Type": "CARD",
        "Department": "Acad Sup Prog For Stu Athl",
        "PersonnelType": "STUDENT",
        "ProxCardID": "0358419",
        "CIDC": "200075736:0",
        "UpdateTimeStamp": datetime.datetime.strptime("2023-08-30 12:46:55", DATE_FMT),
    },
]


FAKE_CCURE_DATA = [
    {
        "CardInt1": 760832,
        "Text1": "200466918",
        "FirstName": "Anthony",
        "LastName": "Inman",
        "MiddleName": "Laine",
        "Text16": "JR",
        "Text14": "alinman@ncsu.edu",
        "Department": "Wellness and Recreation",
        "PersonnelType": "STUDENT",
        "CardNumber": "0359443",
        "text12": "200466918:0",
    },
    {
        "CardInt1": 659310,
        "Text1": "200075736",
        "FirstName": "Jessica",
        "LastName": "Wadsack-Stewart",
        "MiddleName": "Lynn",
        "Text16": "GR",
        "Text14": "jlwadsac@ncsu.edu",
        "Department": "Acad Sup Prog For Stu Athl",
        "PersonnelType": "STUDENT",
        "CardNumber": "0358419",
        "text12": "200075736:0",
    },
    {
        "CardInt1": 769747,
        "Text1": "001133385",
        "FirstName": "Kristen",
        "LastName": "Culbreath",
        "MiddleName": "Taylor",
        "Text16": "TMP",
        "Text14": "kculbre2@ncsu.edu",
        "Department": "DELTA Marketing",
        "PersonnelType": "TEMPORARY EMPLOYEE",
        "CardNumber": "0358536",
        "text12": "001133385:0",
    },
]
