# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.20.1'  # type: str
__version_tuple__ = version_tuple = (1, 20, 1)  # type: tuple[int | str, ...]
