# coding: utf-8

"""
    Ostatní dokumenty CITES

    Toto je API pro Domino konektor ostatních dokumentů CITES  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from citesdoc.api_client import ApiClient


class AdminsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_template(self, doc_code, **kwargs):  # noqa: E501
        """Odstraní položku šablony PDF (cruD)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_template(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_template_with_http_info(doc_code, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_template_with_http_info(doc_code, **kwargs)  # noqa: E501
            return data

    def delete_template_with_http_info(self, doc_code, **kwargs):  # noqa: E501
        """Odstraní položku šablony PDF (cruD)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_template_with_http_info(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['doc_code']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'doc_code' is set
        if ('doc_code' not in params or
                params['doc_code'] is None):
            raise ValueError("Missing the required parameter `doc_code` when calling `delete_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'doc_code' in params:
            path_params['docCode'] = params['doc_code']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/plain; charset=utf-8'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/template/{docCode}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_template(self, doc_code, **kwargs):  # noqa: E501
        """Vrátí šablonu PDF (cRud)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_template(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_template_with_http_info(doc_code, **kwargs)  # noqa: E501
        else:
            (data) = self.get_template_with_http_info(doc_code, **kwargs)  # noqa: E501
            return data

    def get_template_with_http_info(self, doc_code, **kwargs):  # noqa: E501
        """Vrátí šablonu PDF (cRud)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_template_with_http_info(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['doc_code']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'doc_code' is set
        if ('doc_code' not in params or
                params['doc_code'] is None):
            raise ValueError("Missing the required parameter `doc_code` when calling `get_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'doc_code' in params:
            path_params['docCode'] = params['doc_code']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/pdf', 'application/json', 'text/plain; charset=utf-8'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/template/{docCode}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_template_list(self, **kwargs):  # noqa: E501
        """Vrací seznam šablon  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_template_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[TemplateType]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_template_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_template_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_template_list_with_http_info(self, **kwargs):  # noqa: E501
        """Vrací seznam šablon  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_template_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[TemplateType]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_template_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/plain; charset=utf-8'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/template', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[TemplateType]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_template_item(self, **kwargs):  # noqa: E501
        """Zavede novou položku šablony (Crud)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_template_item(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TemplateType body: Definice šablony
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_template_item_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.post_template_item_with_http_info(**kwargs)  # noqa: E501
            return data

    def post_template_item_with_http_info(self, **kwargs):  # noqa: E501
        """Zavede novou položku šablony (Crud)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_template_item_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param TemplateType body: Definice šablony
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_template_item" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/plain; charset=utf-8'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/template', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_template(self, doc_code, **kwargs):  # noqa: E501
        """Nahraje soubor se šablonou PDF nebo změní definici šablony (crUd)  # noqa: E501

        Toto je jediný způsob, jak uplodovat soubory se šablonami  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_template(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :param Object body: Upload soubor PDF nebo JRXML, případně ZIP u vícesouborové šablony
        :param bool enclosure: Indikátor, zda se jedná o šablonu přílohy nebo první stránky
        :param str filename: Nový název souboru. Pokud není zadáno, použije se název uložený v systému
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_template_with_http_info(doc_code, **kwargs)  # noqa: E501
        else:
            (data) = self.put_template_with_http_info(doc_code, **kwargs)  # noqa: E501
            return data

    def put_template_with_http_info(self, doc_code, **kwargs):  # noqa: E501
        """Nahraje soubor se šablonou PDF nebo změní definici šablony (crUd)  # noqa: E501

        Toto je jediný způsob, jak uplodovat soubory se šablonami  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_template_with_http_info(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :param Object body: Upload soubor PDF nebo JRXML, případně ZIP u vícesouborové šablony
        :param bool enclosure: Indikátor, zda se jedná o šablonu přílohy nebo první stránky
        :param str filename: Nový název souboru. Pokud není zadáno, použije se název uložený v systému
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['doc_code', 'body', 'enclosure', 'filename']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'doc_code' is set
        if ('doc_code' not in params or
                params['doc_code'] is None):
            raise ValueError("Missing the required parameter `doc_code` when calling `put_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'doc_code' in params:
            path_params['docCode'] = params['doc_code']  # noqa: E501

        query_params = []
        if 'enclosure' in params:
            query_params.append(('enclosure', params['enclosure']))  # noqa: E501
        if 'filename' in params:
            query_params.append(('filename', params['filename']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/plain; charset=utf-8'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/pdf', 'application/xml', 'application/octet-stream', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/template/{docCode}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_template(self, doc_code, **kwargs):  # noqa: E501
        """Nahraje soubor se šablonou PDF nebo změní definici šablony (crUd)  # noqa: E501

        Toto je jediný způsob, jak uplodovat soubory se šablonami  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_template(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :param Object body: Upload soubor PDF nebo JRXML, případně ZIP u vícesouborové šablony
        :param bool enclosure: Indikátor, zda se jedná o šablonu přílohy nebo první stránky
        :param str filename: Nový název souboru. Pokud není zadáno, použije se název uložený v systému
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_template_with_http_info(doc_code, **kwargs)  # noqa: E501
        else:
            (data) = self.put_template_with_http_info(doc_code, **kwargs)  # noqa: E501
            return data

    def put_template_with_http_info(self, doc_code, **kwargs):  # noqa: E501
        """Nahraje soubor se šablonou PDF nebo změní definici šablony (crUd)  # noqa: E501

        Toto je jediný způsob, jak uplodovat soubory se šablonami  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_template_with_http_info(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :param Object body: Upload soubor PDF nebo JRXML, případně ZIP u vícesouborové šablony
        :param bool enclosure: Indikátor, zda se jedná o šablonu přílohy nebo první stránky
        :param str filename: Nový název souboru. Pokud není zadáno, použije se název uložený v systému
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['doc_code', 'body', 'enclosure', 'filename']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'doc_code' is set
        if ('doc_code' not in params or
                params['doc_code'] is None):
            raise ValueError("Missing the required parameter `doc_code` when calling `put_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'doc_code' in params:
            path_params['docCode'] = params['doc_code']  # noqa: E501

        query_params = []
        if 'enclosure' in params:
            query_params.append(('enclosure', params['enclosure']))  # noqa: E501
        if 'filename' in params:
            query_params.append(('filename', params['filename']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/plain; charset=utf-8'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/pdf', 'application/xml', 'application/octet-stream', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/template/{docCode}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_template(self, doc_code, **kwargs):  # noqa: E501
        """Nahraje soubor se šablonou PDF nebo změní definici šablony (crUd)  # noqa: E501

        Toto je jediný způsob, jak uplodovat soubory se šablonami  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_template(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :param Object body: Upload soubor PDF nebo JRXML, případně ZIP u vícesouborové šablony
        :param bool enclosure: Indikátor, zda se jedná o šablonu přílohy nebo první stránky
        :param str filename: Nový název souboru. Pokud není zadáno, použije se název uložený v systému
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_template_with_http_info(doc_code, **kwargs)  # noqa: E501
        else:
            (data) = self.put_template_with_http_info(doc_code, **kwargs)  # noqa: E501
            return data

    def put_template_with_http_info(self, doc_code, **kwargs):  # noqa: E501
        """Nahraje soubor se šablonou PDF nebo změní definici šablony (crUd)  # noqa: E501

        Toto je jediný způsob, jak uplodovat soubory se šablonami  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_template_with_http_info(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :param Object body: Upload soubor PDF nebo JRXML, případně ZIP u vícesouborové šablony
        :param bool enclosure: Indikátor, zda se jedná o šablonu přílohy nebo první stránky
        :param str filename: Nový název souboru. Pokud není zadáno, použije se název uložený v systému
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['doc_code', 'body', 'enclosure', 'filename']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'doc_code' is set
        if ('doc_code' not in params or
                params['doc_code'] is None):
            raise ValueError("Missing the required parameter `doc_code` when calling `put_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'doc_code' in params:
            path_params['docCode'] = params['doc_code']  # noqa: E501

        query_params = []
        if 'enclosure' in params:
            query_params.append(('enclosure', params['enclosure']))  # noqa: E501
        if 'filename' in params:
            query_params.append(('filename', params['filename']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/plain; charset=utf-8'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/pdf', 'application/xml', 'application/octet-stream', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/template/{docCode}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_template(self, doc_code, **kwargs):  # noqa: E501
        """Nahraje soubor se šablonou PDF nebo změní definici šablony (crUd)  # noqa: E501

        Toto je jediný způsob, jak uplodovat soubory se šablonami  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_template(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :param Object body: Upload soubor PDF nebo JRXML, případně ZIP u vícesouborové šablony
        :param bool enclosure: Indikátor, zda se jedná o šablonu přílohy nebo první stránky
        :param str filename: Nový název souboru. Pokud není zadáno, použije se název uložený v systému
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_template_with_http_info(doc_code, **kwargs)  # noqa: E501
        else:
            (data) = self.put_template_with_http_info(doc_code, **kwargs)  # noqa: E501
            return data

    def put_template_with_http_info(self, doc_code, **kwargs):  # noqa: E501
        """Nahraje soubor se šablonou PDF nebo změní definici šablony (crUd)  # noqa: E501

        Toto je jediný způsob, jak uplodovat soubory se šablonami  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_template_with_http_info(doc_code, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DocumentCode doc_code: (required)
        :param Object body: Upload soubor PDF nebo JRXML, případně ZIP u vícesouborové šablony
        :param bool enclosure: Indikátor, zda se jedná o šablonu přílohy nebo první stránky
        :param str filename: Nový název souboru. Pokud není zadáno, použije se název uložený v systému
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['doc_code', 'body', 'enclosure', 'filename']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_template" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'doc_code' is set
        if ('doc_code' not in params or
                params['doc_code'] is None):
            raise ValueError("Missing the required parameter `doc_code` when calling `put_template`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'doc_code' in params:
            path_params['docCode'] = params['doc_code']  # noqa: E501

        query_params = []
        if 'enclosure' in params:
            query_params.append(('enclosure', params['enclosure']))  # noqa: E501
        if 'filename' in params:
            query_params.append(('filename', params['filename']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/plain; charset=utf-8'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/pdf', 'application/xml', 'application/octet-stream', 'application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['apiKey']  # noqa: E501

        return self.api_client.call_api(
            '/template/{docCode}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
