from .byteplus_ruten_ad_pb2 import (
    User,
    WriteUsersRequest,
    UserError,
    WriteUsersResponse,
    Product,
    WriteProductsRequest,
    ProductError,
    WriteProductsResponse,
    UserEvent,
    WriteUserEventsRequest,
    UserEventError,
    WriteUserEventsResponse,
    Advertisement,
    WriteAdvertisementsRequest,
    AdvertisementError,
    WriteAdvertisementsResponse,
)
